version: '3.8'

services:
    app:
        build: .
        container_name: nest-url-shortener
        ports:
            - '3000:3000'
        env_file:
            - .env
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: shortener
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '33061:3306'
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: redis_cache
        restart: unless-stopped
        ports:
            - '6379:6379'

volumes:
    mysql_data:
