version: '3.8'

services:
    # app:
    #     build: .
    #     container_name: nest-url-shortener
    #     ports:
    #         - '3001:3001'
    #     env_file:
    #         - .env
    #     depends_on:
    #         - mysql
    #         - redis
    #     networks:
    #         - nestnet

    mysql:
        image: mysql
        container_name: mysql_db
        environment:
            MYSQL_DATABASE: url-shortener
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3307:3306'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - nestnet

    redis:
        image: redis:alpine
        container_name: redis_cache
        restart: unless-stopped
        ports:
            - '6379:6379'
        networks:
            - nestnet

networks:
    nestnet:
        driver: bridge

volumes:
    mysql_data:
